version: '3.8'

services:
  backend:
    build: .
    container_name: blogs-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped    
    networks:
      - blog-network  # 使用外部网络         # ✅ 显式设置工作目录，防止某些环境触发配置 bug

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user594  
      POSTGRES_PASSWORD: user395594
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - blog-network  # 使用外部网络

volumes:
  pgdata:

networks:
  blog-network:
    external: true  # 使用外部网络