version: '3.8'

services:
  backend:
    build: .
    container_name: blogs-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
